spring:
  main:
    banner-mode: off
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./config/data # H2 database storing torrent metadata and scanned files
    driverClassName: org.h2.Driver

springdoc:
  writerWithDefaultPrettyPrinter: true
  writerWithOrderByKeys: true
server.port: 8080
torrent:
  downloadPath: config/downloads # Directory where libtorrent will download new files to
  resumePath: config/resume # Directory where libtorrent resume data is stored
  contentPaths: # Directories that are scanned for BitTorrent metadata (.torrent) and content files for seeding
    - config/content
  fileScanInterval: PT1H # How frequently contentPaths are scanned
  activeLimit: 10